-- MRZ Perfume — schéma Supabase
-- À coller dans : Supabase → SQL Editor → New query → Run

create extension if not exists "pgcrypto";

-- Collections (maisons / catégories)
create table if not exists public.collections (
  id text primary key,
  slug text not null unique,
  name text not null,
  description text default '',
  image text default '',
  tone text default 'dark',
  created_at timestamptz not null default now()
);

-- Produits
create table if not exists public.products (
  id bigint primary key,
  name text not null,
  slug text not null unique,
  price numeric(10, 2) not null default 0,
  image text default '',
  brand text default '',
  category text default '',
  category_slug text default '',
  collection text default '',
  collection_slug text default '',
  volume text,
  sizes jsonb not null default '[]'::jsonb,
  in_stock boolean not null default true,
  featured boolean not null default false,
  new_product boolean not null default false,
  fragrance_notes text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_collection_slug_idx
  on public.products (collection_slug);
create index if not exists products_featured_idx
  on public.products (featured);
create index if not exists products_new_product_idx
  on public.products (new_product);

-- Commandes
create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  customer jsonb not null default '{}'::jsonb,
  note text default '',
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0
);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);
create index if not exists orders_status_idx
  on public.orders (status);

-- Témoignages
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Comptes clients (auth locale côté site, stockée en base)
create table if not exists public.customers (
  email text primary key,
  first_name text not null,
  last_name text default '',
  password_hash text not null,
  created_at timestamptz not null default now()
);

-- updated_at auto
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

-- Accès public (clé anon) pour lecture boutique + écriture admin / commandes
-- À durcir plus tard avec Auth Supabase si besoin.
alter table public.collections enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.testimonials enable row level security;
alter table public.customers enable row level security;

drop policy if exists "collections_all" on public.collections;
create policy "collections_all" on public.collections
  for all using (true) with check (true);

drop policy if exists "products_all" on public.products;
create policy "products_all" on public.products
  for all using (true) with check (true);

drop policy if exists "orders_all" on public.orders;
create policy "orders_all" on public.orders
  for all using (true) with check (true);

drop policy if exists "testimonials_all" on public.testimonials;
create policy "testimonials_all" on public.testimonials
  for all using (true) with check (true);

drop policy if exists "customers_all" on public.customers;
create policy "customers_all" on public.customers
  for all using (true) with check (true);
